### PR TITLE
Dublin -- Now with Angular Templates

### PR DESCRIPTION
**Pull request by mtpain**
I have fixed formatting and being able to switch between ISO/DC by pressing the right button at the top.   Since this further clutters the already-cluttered nav bar, I have made navigation enhancement and de-cluttering a new issue assigned to myself: #76

Now [frontend/index.html](https://github.com/northwest-knowledge-network/mdedit/blob/dublin/frontend/index.html) uses Angular templates (or "partials") as explained in the [Angular tutorials](https://docs.angularjs.org/tutorial/step_08) and [Angular API Docs](https://docs.angularjs.org/api/ng/directive/ngInclude). 

This results in greater encapsulation which will allow us more flexibility.  For example, the list of current records is in a template which may simply be moved to a whole separate view just by changing where we place 

```html
<div ng-include="partials/recordsList.html"></div>
```

instead of having to cut and paste the HTML itself.

This doesn't totally finish #71, but it gets us part way there and deserves a review.

### CODE REVIEW

**Comment by mtpain** [comment]
I added a commit that fixes the MILES default utility overwriting fields other than the ones for which default MILES values are defined.

**Comment by mguarinello** [comment]
@mtpain 
Nice work!
But, there are a couple things that need to be fixed before we merge this branch into master. I tried to figure out how to fix these but couldn't get it- I think it has something to do with the new multiple html documents format.
**note- I made a few small changes, so you will need to pull the current dublin before testing and fixing

1) when the record is valid the show/hide functions for the Publish to NKN and Fix errors before Publishing are not working. 
2) for some reason for new records the first pub date is now 12/31/2014 instead of today's date.
3) and a question - did you make any changes to gpt insert so the editor "knows" which type of record to publish. I think this is not part of this pull request, which is fine. I think the first step will be to find a way to create a 'type' attribute for each record so it can be identified as for data or research product.

**Comment by mtpain** [comment]
I did not make any changes to gpt insert.  I agree and think there are some preliminary things to do and plan before we enable publishing as a dublin core record.  Maybe we can plan it out next week.

Thanks for the heads up on the other two items. For 1), is it not working for only DC or for both ISO and DC?

**Comment by mguarinello** [comment]
It is both. I went ahead and did the merge b/c I want to start working on adding the map component today. Let's touch base Monday.

**Comment by mtpain** [comment]
Ok, strange, I can probably fix that today.  I won't be in Monday, but I will be Tuesday.

**Comment by mguarinello** [comment]
Ok


Marisa Guarinello
Environmental Data Manager
MILES EPSCoR Project
Northwest Knowledge Network
University of Idaho, Office of Research & Economic Development
mguarinello@uidaho.edu
208-885-5044

**Pull request merged**
