### PR TITLE
Second round: Issues 46 37 30 45 24 21

### LINKED ISSUE #37: Online Resource Link Field
The field should be call "Online Resources" 
The instructions should be "Is your data or any additional information specific to the data available online or is your data provided as a web service (e.g., Web Mapping Services, Catalog Services for the web, REST services). Provide the url for each online resource."
This should be at the bottom of the Access Contacts block and should be enabled to add more than one.

### PR DESCRIPTION
**Pull request by mtpain**
Should fix #37 and #30. Includes updates from Pull Request #54

### CODE REVIEW

**Comment by mtpain** [comment]
Current fixes are here for #46 (so includes #54 updates), #30, #37, and #45

**Comment by mtpain** [comment]
Should fix Issues #46 #37 #30 #45 #24 #21

**Comment by mguarinello** [comment]
2 things before we can merge this pull request:
1) input from @flathers on the date/time format in #46 
2) mdedit xml topic category is an older versions here. it needs to be updated to be the item/word format that will allow for multiple entries. @mtpain to fix.
Otherwise, it looks great! I will close the issues that are fixed, but leave this pull request open at the moment.

**Comment by mtpain** [comment]
@mguarinello issue with topic_category should be fixed with latest commit

**Pull request merged**
