### PR TITLE
Angular

### LINKED ISSUE #22: Add space and time extent fields
Fields to add are: 
West Longitude
East Longitude
South Latitude
North Latitude
Start Date
End Date
These will need to be constrained to value types.
Can default spatial fields for Idaho bounding box, be sure to note in form instructions
-117.531786
-110.655421
41.946097
49.039542

### PR DESCRIPTION
**Pull request by mtpain**
Should fix #22, #19, #29, #9, #23, #12.

To run the updated version, drop the current metadata you have on your system by first starting a MongoDB shell

```
mongo
```

then run the following mongo commands to remove the old metadata you currently have

```
> use metadata
> db.metadata.drop()
```

Then run ./startup.py and both serves should start as expected. Visit [http://localhost:8000](http://locahost:8000) to see the updated metadata editor.

### CODE REVIEW

**Comment by mguarinello** [comment]
Thank you for these changes.
Issues #9, #23, #12 are fixed with the changes in this branch. I will close these issues.
Issue #22 includes field for vertical extent, min and max. These can be punted to a later time, but please make a new issue for them so they are tracked.
Issue #19 date field encoding---This looks to be fixed but I could not confirm since I couldn't see the xml results from the form (as we discussed at the end of the day)
Issue #29 Please make a new issue for the save and come back to your work later. The functionality has been added to only display the Submit button when all field are filled in. However, this means that the default text in some fields are allowed to pass through into the final form. Instructions should not be provided in the field themselves but as static un-editable text above (see Design Doc Excel for instructions that should be used, used the version in master). We don't want people to just add their email and then be able to submit the form. Maybe what we need are two options: 1) save and return to finish later, in which there are no requirements for completed fields beyond what is needed to save it to their 'account' (if that is the structure), and 2) submit record for publication, required fields (indicated in design doc) must be filled in in order to submit, this submits it to our system and initiates the conversion and validation processes; they will still be able to edit it later though. Does that sound like a plan?

**Comment by mtpain** [comment]
OK, sounds like a good plan. 

As for #29, I see that I missed #20 "Add instructions based on design document". My mistake, I'll get it done for this version.

Re: #22, I can easily put in vertical extents. Do we  want these to be required? I guess elevation is important no matter what.

Sounds like we should show the users an empty form when they create a new document. Then they can follow your instructions and do one of those two options. Saving their work will do the same thing it does now: write the changes to the database for that record. In the future, we'll add an option to publish to NKN? 

In that case, what we really need is an issue for publishing to NKN, is that right? Since you've been publishing data/metadata manually, maybe you should create the issue for that and add some details on the workflow? We did some quick research and there is a Python API for OwnCloud we could maybe use, or we can script transfer whatever way works. However we do it, let's put this in a future milestone as this will be a big change in itself.

**Comment by mguarinello** [comment]
Yes to all those things. Except vertical extents should be optional. It is used more for elevation related data and not all datasets.

Should I accept the pull request and you will move these items to new issues?


Marisa Guarinello
Environmental Data Manager
MILES EPSCoR Project
Northwest Knowledge Network
University of Idaho, Office of Research & Economic Development
mguarinello@uidaho.edu
208-885-5044

**Comment by mtpain** [comment]
OK, added instructions based on design doc and hopefully have field names as they should be. Vertical extents are included (#22). Users can no longer submit default metadata, most every field (dates excluded for now not for any particularly good reason along with default bounding box) must be filled out before a new record can be submitted. 

We'll have to change the language and add some instruction on the different types of submission we'll allow, as we talked about in #29. I created a new issue to add the option to finalize a record and publish to the NKN portal:  #36

**Comment by mguarinello** [comment]
This is very close and looks good.
The vertical extent fields need to be set for floating point type entry. This is noted in the issue too.
Once that and the XML button are fixed, I think it will be ready to accept and merge.
Figuring out how to parse the keywords in the XSLT is my next task, but I think it can be on another branch if you want to go ahead and get this into master.

**Comment by mguarinello** [comment]
So I figured out how to parse keywords in the xslt, but an adjustment is needed to how the generic xml from mdedit is output. From looking at the files, it looks like it might be something in models.py and another files, but I can't tell how to make the changes for the layout of the XML.

**Comment by mtpain** [comment]
@mguarinello I think we have #8 fixed, the XML link is working, and vertical extents can be specified to seven decimal places.

**Pull request merged**
